sudo: required
services:
  - docker

before_install:
  - docker build -t cohenshay/docker-aws -f Dockerfile.dev .

script:
  - docker run  cohenshay/docker-aws npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-aws"
  env: "DockerAws-env"
  bucket_name: "elasticbeanstalk-us-east-2-922963823740"
  bucket_path: "docker-aws"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
   secure: $AWS_SECRET_KEY